### ISSUE TITLE
How to deploy the .zip package to Lambda?

### ISSUE THREAD

**Issue by wtznc** [flolas/aws-lambda-selenium-python311#1]
Thank you for creating a process that automatically generates a complete package ready to be uploaded to S3. I am curious about the next steps. Should I add this package as a layer when creating a new function on Lambda or is there another recommended method?

**Comment by flolas** [comment]
@wtznc you can import the generated zip from local machine using AWS Console. See _"Creating and updating functions with .zip files using the console"_ from aws docs [Creating and updating Python Lambda functions using .zip files](https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-create-update).

You can also create a AWS Lambda Layer with the binaries, as you said, that would be a better approach.

**Comment by wtznc** [comment]
Thanks for getting back to me, problem solved :)
